// DEMO DATA — proposed mappings for the guided walkthrough. For the sample
// dataset these are correct by construction; a real import would compute
// confidence from actual field-level inference, not a fixed constant.

export type OntologyRole = "class" | "relationship" | "attribute";

export interface MappingDefinition {
  sourceDataset: string;
  sourceField: string;
  inferredType: string;
  businessConcept: string;
  ontologyRole: OntologyRole;
  technicalNote: string;
  confidence: number;
}

export const mappingDefinitions: MappingDefinition[] = [
  {
    sourceDataset: "suppliers.csv",
    sourceField: "supplier_id",
    inferredType: "Identifier",
    businessConcept: "Supplier identifier",
    ontologyRole: "attribute",
    technicalNote: "Primary key for the Supplier entity class.",
    confidence: 0.99,
  },
  {
    sourceDataset: "suppliers.csv",
    sourceField: "supplier_name",
    inferredType: "Text",
    businessConcept: "Supplier name",
    ontologyRole: "attribute",
    technicalNote: "Display attribute on the Supplier entity class.",
    confidence: 0.98,
  },
  {
    sourceDataset: "suppliers.csv",
    sourceField: "region_id",
    inferredType: "Foreign key",
    businessConcept: "Located in Region",
    ontologyRole: "relationship",
    technicalNote: "Relationship: Supplier —LOCATED_IN→ Region.",
    confidence: 0.97,
  },
  {
    sourceDataset: "materials.csv",
    sourceField: "material_id",
    inferredType: "Identifier",
    businessConcept: "Material identifier",
    ontologyRole: "attribute",
    technicalNote: "Primary key for the Material entity class.",
    confidence: 0.99,
  },
  {
    sourceDataset: "materials.csv",
    sourceField: "supplier_id",
    inferredType: "Foreign key",
    businessConcept: "Supplied by Supplier",
    ontologyRole: "relationship",
    technicalNote: "Relationship: Supplier —SUPPLIES→ Material.",
    confidence: 0.98,
  },
  {
    sourceDataset: "products.csv",
    sourceField: "material_id",
    inferredType: "Foreign key",
    businessConcept: "Uses Material",
    ontologyRole: "relationship",
    technicalNote: "Relationship: Product —USES→ Material.",
    confidence: 0.98,
  },
  {
    sourceDataset: "products.csv",
    sourceField: "facility_id",
    inferredType: "Foreign key",
    businessConcept: "Assembled at Facility",
    ontologyRole: "relationship",
    technicalNote: "Relationship: Product —ASSEMBLED_AT→ Facility.",
    confidence: 0.97,
  },
  {
    sourceDataset: "revenue_exposure.csv",
    sourceField: "product_id",
    inferredType: "Foreign key",
    businessConcept: "Revenue generated by Product",
    ontologyRole: "relationship",
    technicalNote:
      "Relationship: Product —GENERATES_REVENUE→ Revenue Exposure.",
    confidence: 0.96,
  },
  {
    sourceDataset: "risk_events.csv",
    sourceField: "region_id",
    inferredType: "Foreign key",
    businessConcept: "Risk affects Region",
    ontologyRole: "relationship",
    technicalNote: "Relationship: Risk Event —AFFECTS→ Region.",
    confidence: 0.96,
  },
  {
    sourceDataset: "supply_agreements.csv",
    sourceField: "material_id",
    inferredType: "Foreign key",
    businessConcept: "Agreement covers Material",
    ontologyRole: "relationship",
    technicalNote: "Relationship: Supply Agreement —COVERS→ Material.",
    confidence: 0.97,
  },
];
