"""OQI5-I1 `RemediationCandidate` (CDD-043 Sec12): immutable,
deterministically-extracted possible corrective values, computed by plain
domain code reading existing OQI1/2/3 persisted evidence only -- never
generated by a model (CDD-043 Sec4, Invariant 7). A candidate with zero
supporting evidence cannot exist (`__post_init__` enforces
`len(supporting_evidence_ids) >= 1`); zero candidates for a case is a
valid, expected outcome routing the case to `STEWARD_INVESTIGATION`
(Sec12) -- the engine never fabricates a value absent supporting evidence.

Extraction is deliberately N-source generic (CDD-043 Sec4, "N-source
generic, dissent- and missingness-preserving"): `extract_oqi2_candidates`
never assumes exactly two participants, never collapses a majority into a
truth claim (`OQI-P3-002`-adjacent majority!=truth firewall, restated as
CDD-043 Invariant 5), and always surfaces every distinct observed value as
its own candidate with its own support/conflict/missing sets so dissent
is structurally visible, not narrated away."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from uuid import UUID, uuid5

from app.domain.oqi.evaluation import _length_prefixed, canonical_form
from app.domain.oqi.quality_rule import OQI_NAMESPACE
from app.domain.shared.exceptions import ValidationException

_CANDIDATE_IDENTITY_ALGORITHM_VERSION = "OQI_REMEDIATION_CANDIDATE_IDENTITY_V1"
_MAX_ROLE_LENGTH = 64
_MAX_VALUE_LENGTH = 4000


class RemediationCandidateBasis(StrEnum):
    """CDD-043 Sec12: closed, exactly these four. Longest value
    `OQI2_CONSISTENCY` = 16 chars, `String(32)` safe (Artifact Authorization
    Sec7)."""

    OQI1_COMPLETENESS = "OQI1_COMPLETENESS"
    OQI1_VALIDITY = "OQI1_VALIDITY"
    OQI2_CONSISTENCY = "OQI2_CONSISTENCY"
    OQI3_BUSINESS_RULE = "OQI3_BUSINESS_RULE"


def _sorted_unique(ids: Sequence[UUID]) -> tuple[UUID, ...]:
    return tuple(sorted(set(ids)))


def derive_remediation_candidate_id(
    *,
    case_id: UUID,
    target_source_object_id: UUID,
    target_source_field_id: UUID,
    proposed_value: str,
    supporting_evidence_ids: Sequence[UUID],
) -> UUID:
    """CDD-043 Sec12: deterministic digest of case + target + proposed
    value + supporting-evidence set, role-sorted (evidence IDs sorted, not
    insertion-ordered) so query result order never affects identity."""
    sorted_evidence = _sorted_unique(supporting_evidence_ids)
    material = (
        _length_prefixed(_CANDIDATE_IDENTITY_ALGORITHM_VERSION)
        + _length_prefixed(str(case_id))
        + _length_prefixed(str(target_source_object_id))
        + _length_prefixed(str(target_source_field_id))
        + _length_prefixed(canonical_form(proposed_value))
        + _length_prefixed(str(len(sorted_evidence)))
        + "".join(_length_prefixed(str(evidence_id)) for evidence_id in sorted_evidence)
    )
    return uuid5(OQI_NAMESPACE, material)


@dataclass(frozen=True, slots=True)
class RemediationCandidate:
    candidate_id: UUID
    case_id: UUID
    target_source_object_id: UUID
    target_source_field_id: UUID
    proposed_value: str
    supporting_evidence_ids: tuple[UUID, ...]
    conflicting_evidence_ids: tuple[UUID, ...]
    missing_participant_roles: tuple[str, ...]
    authority_participant_role: str | None
    basis: RemediationCandidateBasis
    extracted_at: datetime

    def __post_init__(self) -> None:
        if not isinstance(self.candidate_id, UUID):
            raise ValidationException("candidate_id must be a UUID")
        if not isinstance(self.case_id, UUID):
            raise ValidationException("case_id must be a UUID")
        if not isinstance(self.target_source_object_id, UUID):
            raise ValidationException("target_source_object_id must be a UUID")
        if not isinstance(self.target_source_field_id, UUID):
            raise ValidationException("target_source_field_id must be a UUID")
        if not isinstance(self.proposed_value, str) or not (
            1 <= len(self.proposed_value) <= _MAX_VALUE_LENGTH
        ):
            raise ValidationException("proposed_value must be non-empty bounded text")
        if not isinstance(self.supporting_evidence_ids, tuple) or not all(
            isinstance(e, UUID) for e in self.supporting_evidence_ids
        ):
            raise ValidationException("supporting_evidence_ids must be a tuple of UUIDs")
        if len(self.supporting_evidence_ids) < 1:
            raise ValidationException(
                "a candidate with zero supporting evidence cannot exist (CDD-043 Sec12)"
            )
        if len(set(self.supporting_evidence_ids)) != len(self.supporting_evidence_ids):
            raise ValidationException("supporting_evidence_ids must not contain duplicates")
        if not isinstance(self.conflicting_evidence_ids, tuple) or not all(
            isinstance(e, UUID) for e in self.conflicting_evidence_ids
        ):
            raise ValidationException("conflicting_evidence_ids must be a tuple of UUIDs")
        if not isinstance(self.missing_participant_roles, tuple) or not all(
            isinstance(r, str) and 1 <= len(r) <= _MAX_ROLE_LENGTH
            for r in self.missing_participant_roles
        ):
            raise ValidationException("missing_participant_roles must be a tuple of role strings")
        if self.authority_participant_role is not None and not (
            isinstance(self.authority_participant_role, str)
            and 1 <= len(self.authority_participant_role) <= _MAX_ROLE_LENGTH
        ):
            raise ValidationException("authority_participant_role must be None or a role string")
        if not isinstance(self.basis, RemediationCandidateBasis):
            raise ValidationException("basis must be a RemediationCandidateBasis")
        if self.extracted_at is None or self.extracted_at.tzinfo is None:
            raise ValidationException("extracted_at must include a timezone")

        expected_id = derive_remediation_candidate_id(
            case_id=self.case_id,
            target_source_object_id=self.target_source_object_id,
            target_source_field_id=self.target_source_field_id,
            proposed_value=self.proposed_value,
            supporting_evidence_ids=self.supporting_evidence_ids,
        )
        if self.candidate_id != expected_id:
            raise ValidationException(
                "candidate_id is inconsistent with its own governed semantic identity inputs"
            )


@dataclass(frozen=True, slots=True)
class ParticipantObservation:
    """Plain read-model input to `extract_oqi2_candidates` -- built by the
    repository layer from OQI2's own persisted
    `QualityComparisonEvaluationParticipantORM` /
    `QualityComparisonEvaluationEvidenceORM` /
    `QualityComparisonEvaluationObservationORM` /
    `FieldValueEvidenceORM` rows (read-only; no OQI2 file is modified to
    produce this). `observed_value=None` means the participant's evidence
    was empty/missing for this evaluation (CDD-040 EMPTY sentinel)."""

    role: str
    source_object_id: UUID
    source_field_id: UUID
    observed_value: str | None
    evidence_id: UUID | None
    is_conflicting: bool
    is_missing: bool
    authoritative: bool


def extract_oqi2_candidates(
    *,
    case_id: UUID,
    target_source_object_id: UUID,
    target_source_field_id: UUID,
    participants: Sequence[ParticipantObservation],
    now: datetime,
) -> tuple[RemediationCandidate, ...]:
    """CDD-043 Sec12, N-source generic: one candidate per distinct
    observed value among *conflicting* participants (i.e. the OQI2
    Evaluation's own deterministic conflict/agreement clustering, not a
    re-derivation of it) -- every cluster becomes its own candidate,
    dissent is never collapsed into a single "winning" value, and no
    candidate is ever created for a value with zero supporting evidence.
    Missing participants are recorded on every candidate as shared
    context, never manufactured into a value. If every participant agrees
    (no conflicting observation exists at all), the single agreed value is
    still surfaced as exactly one candidate -- this is the normal
    agreement case, not a special one.

    `target_source_object_id`/`target_source_field_id` identify the one
    disagreeing-or-missing participant this call is proposing corrective
    values *for*; the caller excludes that participant from `participants`
    (the candidate pool is built from every *other* participant's known
    values, never from the target's own current value) -- one call is made
    per remediable participant, so a Finding with several disagreeing
    participants yields several independent candidate groups, each with
    its own fixed target and its own value pool (CDD-043 Sec12)."""
    missing_roles = tuple(sorted(p.role for p in participants if p.is_missing))
    conflicting = [p for p in participants if p.is_conflicting and p.observed_value is not None]
    known_values = [p for p in participants if p.observed_value is not None and not p.is_missing]

    # Group by distinct observed value (role-insensitive, value-keyed) --
    # this is the deterministic "cluster" the OQI2 Evaluation's own
    # conflict/agreement observations already established; extraction
    # here never invents a new clustering algorithm, it only projects
    # the already-governed known-value set into candidate form.
    by_value: dict[str, list[ParticipantObservation]] = {}
    for p in known_values:
        by_value.setdefault(p.observed_value, []).append(p)  # type: ignore[arg-type]

    if not by_value:
        return ()

    all_conflicting_evidence_ids = tuple(
        sorted({p.evidence_id for p in conflicting if p.evidence_id is not None})
    )

    candidates: list[RemediationCandidate] = []
    for value, members in sorted(by_value.items()):
        supporting_evidence_ids = tuple(
            sorted({p.evidence_id for p in members if p.evidence_id is not None})
        )
        if not supporting_evidence_ids:
            continue
        # Conflicting evidence for *this* candidate is every conflicting
        # participant's evidence that did NOT support this value --
        # dissent against this specific candidate is preserved explicitly.
        conflicting_for_this = tuple(
            sorted(
                eid
                for eid in all_conflicting_evidence_ids
                if eid not in set(supporting_evidence_ids)
            )
        )
        authority_role = next((p.role for p in members if p.authoritative), None)
        candidate_id = derive_remediation_candidate_id(
            case_id=case_id,
            target_source_object_id=target_source_object_id,
            target_source_field_id=target_source_field_id,
            proposed_value=value,
            supporting_evidence_ids=supporting_evidence_ids,
        )
        candidates.append(
            RemediationCandidate(
                candidate_id=candidate_id,
                case_id=case_id,
                target_source_object_id=target_source_object_id,
                target_source_field_id=target_source_field_id,
                proposed_value=value,
                supporting_evidence_ids=supporting_evidence_ids,
                conflicting_evidence_ids=conflicting_for_this,
                missing_participant_roles=missing_roles,
                authority_participant_role=authority_role,
                basis=RemediationCandidateBasis.OQI2_CONSISTENCY,
                extracted_at=now,
            )
        )
    return tuple(candidates)


def extract_oqi1_candidates() -> tuple[RemediationCandidate, ...]:
    """CDD-043 Sec12: OQI1 completeness/validity Findings carry no
    cross-source corroborating evidence from which a corrected value could
    be deterministically supported -- a missing value has no candidate
    replacement, and an invalid value has no known-correct alternative,
    without evidence this engine does not fabricate. Always returns zero
    candidates; the case routes to `STEWARD_INVESTIGATION`. This is the
    epistemically honest answer (Sec12: "never fabricates a value absent
    supporting evidence"), not an unimplemented placeholder."""
    return ()


def extract_oqi3_candidates() -> tuple[RemediationCandidate, ...]:
    """CDD-043 Sec12: an OQI3 BusinessRuleFinding violation (e.g. a
    required field missing, or a comparison failing) does not, by itself,
    supply a specific corrective value -- there is no persisted evidence
    saying what the correct value should be, only that the current state
    violates the governed rule. Always returns zero candidates; the case
    routes to `STEWARD_INVESTIGATION` (the business-rule crown scenario:
    Purchasing Group missing, no evidence for what it should be)."""
    return ()
