"use client";

import { useState } from "react";
import { signIn } from "@/lib/auth/browser-session";
import {
  OntologyCopilotApiError,
  ontologyCopilotApi,
} from "@/lib/ontology-copilot/api-client";
import type { AskResponse } from "@/lib/ontology-copilot/contracts";
import { EvidencePath } from "./evidence-path";

type AskState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "unauthorized" }
  | { status: "error"; message: string }
  | { status: "result"; response: AskResponse };

const EXAMPLE_QUESTION = "Which products depend on TSMC?";

export function AskCtecWorkspace() {
  const [question, setQuestion] = useState("");
  const [state, setState] = useState<AskState>({ status: "idle" });

  async function submit(text: string) {
    const trimmed = text.trim();
    if (!trimmed) return;
    setState({ status: "loading" });
    try {
      const response = await ontologyCopilotApi.ask({ question: trimmed });
      setState({ status: "result", response });
    } catch (error) {
      if (error instanceof OntologyCopilotApiError) {
        if (error.problem.code === "AUTH_REQUIRED" || error.status === 401) {
          setState({ status: "unauthorized" });
          return;
        }
        setState({ status: "error", message: error.problem.message });
        return;
      }
      setState({
        status: "error",
        message: "The Ask CTEC service could not be reached.",
      });
    }
  }

  function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    void submit(question);
  }

  return (
    <div>
      <div className="page-heading">
        <div>
          <span className="eyebrow">Ontology Studio</span>
          <h1>Ask CTEC</h1>
          <p>
            Ask a supported question about the governed enterprise ontology.
            Every answer is derived deterministically from persisted,
            tenant-scoped data -- never generated by an LLM.
          </p>
        </div>
      </div>

      <section className="panel" aria-label="Ask CTEC">
        <form
          onSubmit={handleSubmit}
          className="action-row"
          style={{ flexWrap: "wrap" }}
        >
          <label htmlFor="ask-ctec-question" className="sr-only">
            Question
          </label>
          <input
            id="ask-ctec-question"
            type="text"
            value={question}
            onChange={(event) => setQuestion(event.target.value)}
            placeholder={EXAMPLE_QUESTION}
            style={{ flex: "1 1 320px" }}
          />
          <button
            type="submit"
            className="button"
            disabled={state.status === "loading"}
          >
            Ask CTEC
          </button>
        </form>
        <p style={{ color: "var(--muted)", marginTop: "0.5rem" }}>
          Example: <em>{EXAMPLE_QUESTION}</em>
        </p>
      </section>

      {state.status === "loading" && (
        <div className="panel" role="status">
          Thinking through the governed ontology…
        </div>
      )}

      {state.status === "unauthorized" && (
        <div className="panel" role="alert">
          <p style={{ fontWeight: 700 }}>Sign in required</p>
          <p style={{ color: "var(--muted)" }}>
            You must sign in to ask CTEC a question.
          </p>
          <button
            type="button"
            className="button"
            style={{ marginTop: "0.75rem" }}
            onClick={() => void signIn("/ontology-studio/ask")}
          >
            Sign in
          </button>
        </div>
      )}

      {state.status === "error" && (
        <div className="panel error-summary" role="alert">
          <p style={{ fontWeight: 700 }}>Ask CTEC service unavailable</p>
          <p>{state.message}</p>
          <button
            type="button"
            className="secondary"
            style={{ marginTop: "0.75rem" }}
            onClick={() => void submit(question)}
          >
            Retry
          </button>
        </div>
      )}

      {state.status === "result" && <AskResult response={state.response} />}
    </div>
  );
}

function AskResult({ response }: { response: AskResponse }) {
  if (response.status === "unsupported_question") {
    return (
      <div className="panel" role="status" aria-label="Unsupported question">
        <p style={{ fontWeight: 700 }}>
          This question type is not supported yet
        </p>
        <p style={{ color: "var(--muted)" }}>
          CTEC currently supports questions like <em>{EXAMPLE_QUESTION}</em>
        </p>
      </div>
    );
  }

  if (response.status === "no_match") {
    return (
      <div className="panel" role="status" aria-label="No match found">
        <p style={{ fontWeight: 700 }}>No governed evidence found</p>
        <p>{response.answer}</p>
      </div>
    );
  }

  if (response.status === "ambiguous_match") {
    return (
      <div className="panel" role="status" aria-label="Ambiguous match">
        <p style={{ fontWeight: 700 }}>More than one match</p>
        <p>{response.answer}</p>
      </div>
    );
  }

  return (
    <div className="panel" aria-label="Answer">
      <h2>Answer</h2>
      <p style={{ whiteSpace: "pre-line" }}>{response.answer}</p>

      {response.resolved_entity && (
        <p style={{ color: "var(--muted)" }}>
          Resolved to governed entity:{" "}
          <strong>{response.resolved_entity.entity_name}</strong> (
          {response.resolved_entity.entity_type_name})
        </p>
      )}

      {response.evidence.length > 0 && (
        <div style={{ marginTop: "1rem" }}>
          <h3>Why?</h3>
          {response.evidence.map((steps, index) => (
            <div key={index} style={{ marginBottom: "1rem" }}>
              <EvidencePath steps={steps} />
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
