"""Request/response models for the Ask CTEC API (Gate D). Every field comes
from either the caller's own question text or an already-persisted, already
tenant-scoped traversal result -- see
app.application.ontology_copilot_api.OntologyCopilotApiService. No field is
ever generated by an LLM.
"""

from pydantic import BaseModel, ConfigDict, Field


class ClosedModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class AskRequest(ClosedModel):
    question: str = Field(min_length=1, max_length=500)


class ResolvedEntityResponse(BaseModel):
    entity_id: str
    entity_name: str
    entity_type_name: str


class EvidenceStepResponse(BaseModel):
    step: int
    entity_id: str
    entity_name: str
    entity_type_name: str
    relationship_name: str | None


class AskResponse(BaseModel):
    status: str
    intent: str | None
    answer: str
    resolved_entity: ResolvedEntityResponse | None
    result_names: list[str]
    evidence: list[list[EvidenceStepResponse]]
    reason: str | None = None
